/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Clases.FdeSnedecor;

/**
 *
 * @author Matias
 */
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    public Resultados(Double [][] datos) {
        initComponents();
        setLocationRelativeTo(null);
        double [] acumMedias=new double [datos[1].length];
        double [] contMedias=new double [datos[1].length];
        double acumGranMedia=0;
        int contGranMedia=0;
        double GranMedia=0;
        double [] promedios=new double [datos[1].length];
        double [] varianzas=new double [datos[1].length];   
        double [] difdentro=new double [datos[1].length];
        double [] difentre=new double [datos[1].length];
        
        for (int i = 0; i < datos.length; i++) {
            for (int j = 0; j < datos[i].length; j++) {
                if (datos[i][j]!=null) {
                    acumGranMedia += datos[i][j];
                    contGranMedia ++;
                    acumMedias[j]+=datos[i][j];
                    contMedias[j]++;
                }
            }
        }
        GranMedia = acumGranMedia / contGranMedia;
        for (int i = 0; i < promedios.length; i++) {
            promedios[i] = acumMedias[i] / contMedias[i];
        }
        for (int i = 0; i < datos.length; i++) {
            for (int j = 0; j < datos[i].length; j++) {
                if (datos[i][j] != null) {
                    difdentro[j] += Math.pow((datos[i][j] - promedios[j]), 2);
                }
            }
        }
        for (int i = 0; i < difentre.length; i++) {
            difentre[i] = contMedias[i] * (Math.pow((promedios[i] - GranMedia), 2));
        }
        for (int i = 0; i < varianzas.length; i++) {
            varianzas[i] = difdentro[i] / (contMedias[i] - 1);
        }

        double SCE = 0;
        double SCD = 0;
        for (int i = 0; i < difentre.length; i++) {
            SCE += difentre[i];
            SCD += difdentro[i];
        }
        double glN=(promedios.length-1);
        double glD=(contGranMedia-promedios.length);
        
        
        double CME=SCE/glN;
        double CMD=SCD/glD;
        
        double FObs=(CME/CMD);
        FdeSnedecor prob= new FdeSnedecor(FObs,glN, glD);
        
        
        tblANOVA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Entre Grupos", String.format("%.4f", SCE), promedios.length-1, String.format("%.4f", CME), String.format("%.4f", FObs), String.format("%.4f", (prob.getpValor()))},
                {"Dentro de Grupos", String.format("%.4f", SCD), contGranMedia-promedios.length, String.format("%.4f", CMD), null, null},
                {"Total", String.format("%.4f", (SCE+SCD)), contGranMedia-1, null, null, null}
            },
            new String [] {
                "Origen de las Variaciones", "Suma de Cuadrados", "GL", "Cuadrados Medios", "Fobs", "P-valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblANOVA.getTableHeader().setReorderingAllowed(false);
        
        lblAlfa.setText("Alfa = "+jSlider1.getValue()+" %" );
        String H0="H0: ";
        for (int i = 0; i < datos[1].length; i++) {
            if (i+1<datos[1].length) {
                H0 +="µ"+(i+1)+" = ";
            }else {
                H0 +="µ"+(i+1);
            }
        }
        lblH0.setText(H0);
        Pval=prob.getpValor();
        
        if (prob.getpValor()< (Double.parseDouble(Integer.valueOf(jSlider1.getValue()).toString())/100)) {
            
            lblConclusion.setText("Alfa("+(Double.parseDouble(Integer.valueOf(jSlider1.getValue()).toString())/100)+") > P-valor("+String.format("%.4f", (prob.getpValor()))+") --- Se rechaza H0");
        }else {
            lblConclusion.setText("Alfa("+(Double.parseDouble(Integer.valueOf(jSlider1.getValue()).toString())/100)+") < P-valor("+String.format("%.4f", (prob.getpValor()))+") --- No se rechaza H0");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblANOVA = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        lblAlfa = new javax.swing.JLabel();
        lblH0 = new javax.swing.JLabel();
        lblH1 = new javax.swing.JLabel();
        lblTablaAnova = new javax.swing.JLabel();
        lblConclusion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblANOVA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, ""},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblANOVA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 90));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jSlider1.setMaximum(30);
        jSlider1.setValue(5);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 380, -1));

        lblAlfa.setText("jLabel1");
        getContentPane().add(lblAlfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblH0.setText("jLabel1");
        getContentPane().add(lblH0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, -1));

        lblH1.setText("H1: Al menos alguna es distinta");
        getContentPane().add(lblH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, -1));

        lblTablaAnova.setText("Tabla ANOVA");
        getContentPane().add(lblTablaAnova, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lblConclusion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblConclusion.setText("jLabel1");
        getContentPane().add(lblConclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 450, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        lblAlfa.setText("Alfa = "+jSlider1.getValue()+" %" );
        
        if (Pval< (Double.parseDouble(Integer.valueOf(jSlider1.getValue()).toString())/100)) {
            
            lblConclusion.setText("Alfa("+(Double.parseDouble(Integer.valueOf(jSlider1.getValue()).toString())/100)+") > P-valor("+String.format("%.4f", (Pval))+") --- Se rechaza H0");
        }else {
            lblConclusion.setText("Alfa("+(Double.parseDouble(Integer.valueOf(jSlider1.getValue()).toString())/100)+") < P-valor("+String.format("%.4f", (Pval))+") --- No se rechaza H0");
        }
        
    }//GEN-LAST:event_jSlider1MouseDragged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Resultados().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblAlfa;
    private javax.swing.JLabel lblConclusion;
    private javax.swing.JLabel lblH0;
    private javax.swing.JLabel lblH1;
    private javax.swing.JLabel lblTablaAnova;
    private javax.swing.JTable tblANOVA;
    // End of variables declaration//GEN-END:variables
    private static double Pval;
}
